# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Weighted Least Squares in RcppArmadillo.
#'
#' @param X numeric matrix
#' @param y numeric vector
#' @param w numeric vector
#' @return list
lmW <- function(X, y, w) {
    .Call(`_blblm_lmW`, X, y, w)
}

